name: A1 CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'fragments/**'
      - 'fragments-ui/**'
      - '.github/workflows/**'
  push:
    branches: [main]
    paths:
      - 'fragments/**'
      - 'fragments-ui/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fragments
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: fragments/package-lock.json

      - name: Install node dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fragments
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: fragments/package-lock.json

      - name: Install deps and run tests
        run: npm install-ci-test

  ui:
    name: Fragments UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fragments-ui
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: fragments-ui/package-lock.json

      - name: Install node dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build UI
        run: npm run build
